spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: swagger-ui
          uri: lb://TEST-SERVICE
          predicates:
            - Path=/swagger-ui/**,/swagger-resources/**,/swagger-ui.html,/v2/api-docs,/webjars/**,/view/**
server:
  port: 9000
eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

springdoc:
  version: '@springdoc.version@'
  swagger-ui:
    use-root-path: true

