spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: openapi
          uri: http://localhost:${server.port}
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/openapi
        - id: auth-openapi
          uri: lb://AUTHENTICATION-SERVICE
          predicates:
            - Path= /auth-openapi/** , /api/auth/**
          filters:
            - RewritePath=/auth-openapi/(?<path>.*), /api/auth/$\{path}
            - RewritePath=/api/auth/(?<path>.*), /api/auth/$\{path}

server:
  port: 9000
eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


