spring:
  application:
    name: user-service
server:
  port: 8081
eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

springdoc.api-docs.path : /api/user/openapi